version: 0.2

env:
  secrets-manager:
    AWS_ACCESS_KEY_ID: "terraform_user_creds:AWS_ACCESS_KEY_ID"
    AWS_SECRET_ACCESS_KEY: "terraform_user_creds:AWS_SECRET_ACCESS_KEY"

phases:
  install:
    commands:
      - echo Installing pre-requisites
      - sudo apt-get update
      - echo Installing Terraform...
      - sudo apt-get install -y gnupg software-properties-common
      - wget -O- https://apt.releases.hashicorp.com/gpg | gpg --dearmor | sudo tee /usr/share/keyrings/hashicorp-archive-keyring.gpg
      - echo "deb [signed-by=/usr/share/keyrings/hashicorp-archive-keyring.gpg] https://apt.releases.hashicorp.com $(lsb_release -cs) main" | sudo tee /etc/apt/sources.list.d/hashicorp.list
      - sudo apt update
      - sudo apt-get -y install terraform
      - echo Installing Python
      - sudo apt-get -y install python3-pip


  pre_build:
    commands:
      - echo Entering pre-build plase...
      - echo Packaging lambda code...
      - chmod +x ./tf-modules/lambda/scripts/create_pkg.sh
      - ./tf-modules/lambda/scripts/create_pkg.sh eventifyer test
      - ./tf-modules/lambda/scripts/create_pkg.sh batchingester test
      - ./tf-modules/lambda/scripts/create_pkg.sh streamingingester test
      - echo Choose right environment...
      - terraform workspace select test
      - echo Initiating Terraform...
      - terraform init
      - echo Validating terraform...
      - terraform validate

  build:
    commands:
    - echo Deploying terraform infrastructure...
    - terraform apply -auto-approve
      
      